### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "vladimircuriel@outlook.com",
    "password": "amatista",
    "name": "Vladimir Curiel",
    "number": "8295913442",
    "role": "USER"
}

### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "natashamarialopez@gmail.com",
    "password": "NMLC05122028",
    "name": "Mi amor",
    "number": "8094020166",
    "role": "USER"
}

### obtener todos los usuarios
GET http://localhost:3000/users

### obtener un usuario por id
GET http://localhost:3000/users/3fb3f93a-2705-47df-af90-efd87d6b2b19

### obtener a mi amor
GET http://localhost:3000/users/92cebd6c-13cb-4231-98d8-230008de06e6

### modificar un usuario
PATCH  http://localhost:3000/users/574f2610-31a6-4b81-9f18-c8968921e2e0
Content-Type:  application/json

{
    "email": "vladimircurielo@gmail.com"
}

### eliminar un usuario
DELETE http://localhost:3000/users/574f2610-31a6-4b81-9f18-c8968921e2e0


### agregar una pelicula a un usuario
POST http://localhost:3000/users/3fb3f93a-2705-47df-af90-efd87d6b2b19/movies
Content-Type: application/json

{
    "movieId": "329a97f5-7c6c-4b8c-9bf3-5b57b2e95067"
}

### obtener las peliculas de un usuario
GET http://localhost:3000/users/92cebd6c-13cb-4231-98d8-230008de06e6/movies

### obtener las peliculas de un usuario
GET http://localhost:3000/users/3fb3f93a-2705-47df-af90-efd87d6b2b19/movies