### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "vladimircurielooyo@outlook.com",
    "password": "amatista",
    "name": "Vladimir Curiel Ovalles",
    "number": "8295313132",
    "role": "USER"
}

### Crear un usuario admin
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "vladimir@outlook.com",
    "password": "amatista30",
    "name": "Vladimir Curiel Ovalles",
    "number": "8290000000",
    "role": "ADMIN"
}

### obtener una jwt
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "vladimir@outlook.com",
    "password": "amatista30"
}

### entrar a una ruta protegida
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExMDlmZmZhLTllNGMtNDMyZS05YzdhLTc5ODhlZjBkYmQxMSIsIm5hbWUiOiJWbGFkaW1pciBDdXJpZWwgT3ZhbGxlcyIsImVtYWlsIjoidmxhZGltaXJjdXJpZWxvb3lvQG91dGxvb2suY29tIiwibnVtYmVyIjoiODI5NTMxMzEzMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzA1Mjc4MzAyLCJleHAiOjE3MDUyNzkyMDJ9.m5X7vUhZruJIuXkVGrsSQPTHbEEpM2WNuRvx2JAZAlk

### aceder a una ruta de admin
GET http://localhost:3000/auth/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExMDlmZmZhLTllNGMtNDMyZS05YzdhLTc5ODhlZjBkYmQxMSIsIm5hbWUiOiJWbGFkaW1pciBDdXJpZWwgT3ZhbGxlcyIsImVtYWlsIjoidmxhZGltaXJjdXJpZWxvb3lvQG91dGxvb2suY29tIiwibnVtYmVyIjoiODI5NTMxMzEzMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzA1Mjc4MzAyLCJleHAiOjE3MDUyNzkyMDJ9.m5X7vUhZruJIuXkVGrsSQPTHbEEpM2WNuRvx2JAZAlk

### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "natashamarialopez@gmail.com",
    "password": "NMLC05122028",
    "name": "Natasha Lopez",
    "number": "8094020166",
    "role": "USER"
}

### obtener todos los usuarios
GET http://localhost:3000/users

### obtener un usuario por id
GET http://localhost:3000/users/253ffcbe-db6f-49c5-9a82-ffb6e9ab1c27

### modificar un usuario
PATCH  http://localhost:3000/users/253ffcbe-db6f-49c5-9a82-ffb6e9ab1c27
Content-Type:  application/json

{
    "email": "vladimircuriel@gmail.com"
}

### eliminar un usuario
DELETE http://localhost:3000/users/574f2610-31a6-4b81-9f18-c8968921e2e0


### agregar una pelicula a un usuario
POST http://localhost:3000/users/253ffcbe-db6f-49c5-9a82-ffb6e9ab1c27/movies/40ca6dbf-938b-4d51-add5-b4a6fddc05d9
Content-Type: application/json


### obtener las peliculas de un usuario
GET http://localhost:3000/users/253ffcbe-db6f-49c5-9a82-ffb6e9ab1c27/movies

### obtener las peliculas de un usuario
GET http://localhost:3000/users/253ffcbe-db6f-49c5-9a82-ffb6e9ab1c27/movies

### obtener un jwt
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "vladimircurielooyo@outlook.com",
    "password": "amatista"
}

### acceder a una ruta protegida
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZmE4ZjIxLTIyYTktNGI4ZS1hYTc1LTFlZjc2MzA2NWFjZSIsIm5hbWUiOiJWbGFkaW1pciBDdXJpZWwgT3ZhbGxlcyIsImVtYWlsIjoidmxhZGltaXJjdXJpZWxvb3lvQG91dGxvb2suY29tIiwibnVtYmVyIjoiODI5NTMxMzEzMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzA1MjQ5ODY0LCJleHAiOjE3MDUyNDk4OTR9.yXk9sStRpsbgDcN5vplpPs6NHq9ReFvCunLPCPuk5x4

### accerder a una ruta protegida 30s
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZmE4ZjIxLTIyYTktNGI4ZS1hYTc1LTFlZjc2MzA2NWFjZSIsIm5hbWUiOiJWbGFkaW1pciBDdXJpZWwgT3ZhbGxlcyIsImVtYWlsIjoidmxhZGltaXJjdXJpZWxvb3lvQG91dGxvb2suY29tIiwibnVtYmVyIjoiODI5NTMxMzEzMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzA1MjQ5OTc0LCJleHAiOjE3MDUyNTAwMDR9.vRK5Ll2owwUvw6mDRzSbWdplRqMfmV-hL6DnoAnmfds
### obtener un jwt nuevo
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZmE4ZjIxLTIyYTktNGI4ZS1hYTc1LTFlZjc2MzA2NWFjZSIsIm5hbWUiOiJWbGFkaW1pciBDdXJpZWwgT3ZhbGxlcyIsImVtYWlsIjoidmxhZGltaXJjdXJpZWxvb3lvQG91dGxvb2suY29tIiwibnVtYmVyIjoiODI5NTMxMzEzMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzA1MjQ5OTY1LCJleHAiOjE3MDY2MzIzNjV9.LEJ3Wh-Soz46_dXavTHSYqpclLfHSC6F-OJCxiT91jA"
}

### obtener usuarios de la ddbb real
GET https://movies-app-production-a6cd.up.railway.app/users

### crear un usuario en la ddbb real
POST https://movies-app-production-a6cd.up.railway.app/users
Content-Type: application/json

{
    "email": "vladimircurielooyo@outlook.com",
    "password": "amatista",
    "name": "Vladimir Curiel Ovalles",
    "number": "8295313132",
    "role": "USER"
}

### crear un usuario en la ddbb real
POST https://movies-app-production-a6cd.up.railway.app/users
Content-Type: application/json

{
    "email": "moise@outlook.com",
    "password": "amatista",
    "name": "Vladimir Curiel Ovalles",
    "number": "3453455563",
    "role": "USER"
}